#Definitions

def setHeaders(contract):
	Sec = []
	if contract == 'GL':
		Sec.append('COVERAGE A BODILY INJURY AND PROPERTY DAMAGE LIABILITY')
		Sec.append('COVERAGE B PERSONAL AND ADVERTISING INJURY LIABILITY')
		Sec.append('COVERAGE C MEDICAL PAYMENTS')
		Sec.append('SUPPLEMENTARY PAYMENTS – COVERAGES A AND B')
		Sec.append('SECTION II – WHO IS AN INSURED')
		Sec.append('SECTION III – LIMITS OF INSURANCE')
		Sec.append('SECTION IV – COMMERCIAL GENERAL LIABILITY CONDITIONS')
		Sec.append('SECTION V – EXTENDED REPORTING PERIODS')
		Sec.append('SECTION VI – DEFINITIONS')
	if contract == 'WC':
		Sec.append('GENERAL SECTION')
		Sec.append('PART ONE - WORKERS COMPENSATION INSURANCE')
		Sec.append('PART TWO - EMPLOYERS LIABILITY INSURANCE')
		Sec.append('PART THREE - OTHER STATES INSURANCE')
		Sec.append('PART FOUR - YOUR DUTIES IF INJURY OCCURS')
		Sec.append('PART FIVE - PREMIUM')
		Sec.append('PART SIX - CONDITIONS')		
	return Sec